LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := dm-tools
LOCAL_MODULE_OWNER := smartisan
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_SRC_FILES := bin/dm-tools
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE := logic_volume
LOCAL_MODULE_OWNER := smartisan
LOCAL_MODULE_PATH := $(TARGET_OUT_EXECUTABLES)
LOCAL_SRC_FILES := bin/logic_volume
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE       := dm-tools.recovery
LOCAL_MODULE_STEM  := dm-tools
LOCAL_MODULE_OWNER := smartisan
LOCAL_MODULE_PATH  := $(TARGET_RECOVERY_ROOT_OUT)/bin
LOCAL_SRC_FILES    := bin/dm-tools
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE       := logic_volume.recovery
LOCAL_MODULE_STEM  := logic_volume
LOCAL_MODULE_OWNER := smartisan
LOCAL_MODULE_PATH  := $(TARGET_RECOVERY_ROOT_OUT)/bin
LOCAL_SRC_FILES    := bin/logic_volume
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := EXECUTABLES
include $(BUILD_PREBUILT)
